# Supabase project configuration.
# https://supabase.com/docs/guides/cli/config

project_id = "gygnshfngcyxkamapejf"

[api]
# Port to use for Supabase API URL
port = 54321
# Schemas to expose in the API. 'public' and 'storage' are required,
# 'graphql_public' is recommended.
schemas = ["public", "storage", "graphql_public"]
# Extra search path for views, functions, etc.
extra_search_path = ["public"]
# Limit for the number of rows returned by a view, table, or function.
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# Use a custom Docker image for the database.
docker_image = "supabase/postgres:15.1.0.118"
# The database major version to use.
# major_version = 16

[studio]
# Port to use for Supabase Studio
port = 54323

# Edge Functions
[functions]
  [functions.kavenegar-otp-sender]
    # To run this function, you need to add KAVEHNEGAR_API_KEY and KAVEHNEGAR_SENDER_NUMBER
    # to your project's secrets:
    # supabase secrets set KAVEHNEGAR_API_KEY=your_api_key
    # supabase secrets set KAVEHNEGAR_SENDER_NUMBER=your_sender_number
    # verify_jwt = false
