# Supabase project configuration.
# https://supabase.com/docs/guides/cli/config

project_id = "rfiybvlqdibtwckbgscu"

[api]
# Port to use for Supabase API URL
port = 54321
# Schemas to expose in the API. 'public' and 'storage' are required,
# 'graphql_public' is recommended.
schemas = ["public", "storage", "graphql_public"]
# Extra search path for views, functions, etc.
extra_search_path = ["public"]
# Limit for the number of rows returned by a view, table, or function.
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# Use a custom Docker image for the database.
docker_image = "supabase/postgres:15.1.0.118"
# The database major version to use.
# major_version = 16

[studio]
# Port to use for Supabase Studio
port = 54323

# This section configures the Kavenegar Edge Function.
# By setting verify_jwt to true, we ensure that the function only accepts
# requests that are securely signed by the Supabase Auth service.
# The JWT secret must be set both in the Auth Hook settings and in the function's secrets.
[functions.kavenegar-otp-sender]
verify_jwt = true
import_map = "./supabase/functions/import_map.json"
