
# Supabase project configuration.
# https://supabase.com/docs/guides/cli/config

project_id = "rfiybvlqdibtwckbgscu"

[api]
# Port to use for Supabase API URL
port = 54321
# Schemas to expose in the API. 'public' and 'storage' are required,
# 'graphql_public' is recommended.
schemas = ["public", "storage", "graphql_public"]
# Extra search path for views, functions, etc.
extra_search_path = ["public"]
# Limit for the number of rows returned by a view, table, or function.
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# Use a custom Docker image for the database.
docker_image = "supabase/postgres:15.1.0.118"
# The database major version to use.
# major_version = 16

[studio]
# Port to use for Supabase Studio
port = 54323

# Declares the Edge Function for sending OTPs
# and ensures JWT verification is enabled.
[functions.kavenegar-otp-sender]
verify_jwt = false

# Temporary logger function to debug hook payloads
[functions.log-catcher]
verify_jwt = false
